api:
  version: 1

spring:
  profiles:
    active: production
    social:
      auto-connection-views: true # not using thymeleaf, so enable
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    jdbc-url: ${spring.datasource.url}
    driver-class-name: org.postgresql.Driver
    username: memetics
    password: memetics
    hikari:
      jdbc-url: ${spring.datasource.url}
      data-source-properties:
        socketTimeout: 120
        tcpKeepAlive: true
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      # Prevent spurious exception java.sql.SQLFeatureNotSupportedException:
      # Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
      #
      # References:
      #
      # [1] https://github.com/pgjdbc/pgjdbc/issues/1102
      # [2] https://hibernate.atlassian.net/browse/HHH-12368
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.jdbc.time_zone: UTC
      hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 400
      javax.persistence.query.timeout: 10000
      javax.persistence.lock.timeout: 10000
      hibernate:
        dialect: ${spring.jpa.database-platform}
    open-in-view: false
  liquibase:
    changeLog: classpath:changelog/db.changelog-master.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true

application:
  url: localhost:8080/memetics

# TODO below properties should be organised better

bearerToken:
idle: 3600000 #1 hour
idleTimeout: 60

redirectUrl: http://localhost:8080/login/oauth2/client/buffer

sendTweetsViaScheduler: false